kentik_user: "email address"
kentik_token: "token"
snmp_user: "username"
snmp_version: "v2" # Options include: v3 or v2.
snmp_auth_protocol: "SHA"
snmp_auth_password: "password"
snmp_priv_protocol: "AES"
snmp_priv_password: "password"
snmp_community: "community"