plugin: netbox.netbox.nb_inventory
api_endpoint: https://yznw9097.cloud.netboxapp.com
validate_certs: False
config_context: False
device_query_filters:
  - has_primary_ip: 'true'
  #- tag: 'tag1'
  #- role: 'edge-router'
