---
- name: "MAIN >> SYNC NAUTOBOT LOCATIONS TO KENTIK SITES"
  hosts: localhost
  connection: local
  gather_facts: false
  # vars_files:
  #   - ./vars/credentials.yml

  tasks:
  
    - name: Create the Site
      kentik_site:
        title: "{{ item['value']['name'] }}"
        lat: "{{ item['value']['latitude'] | float }}"
        lon: "{{ item['value']['longitude'] | float }}"
        postalAddress:
          address: "{{ item['value']['physical_address'] | default('') }}"
          city: "{{ item['value']['parent']['name'] | default('') }}"
          region: "{{ item['value']['parent']['parent']['name'] | default('') }}"
          country: "{{ item['value']['parent']['parent']['parent']['name'] | default('') }}"
        region: "EU"
        state: present
      delegate_to: localhost
      register: site_data
      run_once: true
      loop: "{{ query('networktocode.nautobot.lookup', 'locations',
                        api_endpoint='API_ENDPOINT',
                        api_version='2.0',
                        validate_certs=False,
                        api_filter='name=NAME' + ' depth=3',
                        num_retries=0,
                        token='TOKEN') }}"
    - name: Debug kentik api call
      debug:
        msg: "{{ site_data }}"
      delegate_to: localhost
      run_once: true