---
- name: "MAIN >> SYNC NAUTOBOT TO KENTIK << MUST USE NAUTOBOT INVENTORY"
  hosts: all
  gather_facts: false
  vars_files:
    - ./vars/credentials.yml

  tasks:

    - name: Collect List of Sites from Nautobot
      uri: 
        url: https://10.1.1.12/api/dcim/locations
        validate_certs: false
        headers:
          authorization: Token {{nautobot_token}}
      register: nautobot_sites
      delegate_to: localhost
      run_once: true

    - name: Create the Site
      kentik_site:
        title: "{{ item['name'] }}"
        lat: "{{ item['latitude'] | int }}"
        lon: "{{ item['longitude'] | int }}"
        state: present
      delegate_to: localhost
      register: site_data
      run_once: true
      loop: "{{ nautobot_sites.json.results }}"

    - name: Gather Device Roles from Nautobot
      uri: 
        url: https://10.1.1.12/api/extras/roles
        validate_certs: false
        headers:
          authorization: Token {{nautobot_token}}
      register: nautobot_roles
      delegate_to: localhost
      run_once: true
    
    - name: Gather Tenants from Nautobot
      uri: 
        url: https://10.1.1.12/api/tenancy/tenants
        validate_certs: false
        headers:
          authorization: Token {{nautobot_token}}
      register: nautobot_tenants
      delegate_to: localhost
      run_once: true
    
    - name: Gather Tags from Nautobot
      uri: 
        url: https://10.1.1.12/api/extras/tags
        validate_certs: false
        headers:
          authorization: Token {{nautobot_token}}
      register: nautobot_tags
      delegate_to: localhost
      run_once: true

    - name: Gather Device Types from Nautobot
      uri: 
        url: https://10.1.1.12/api/dcim/device-types
        validate_certs: false
        headers:
          authorization: Token {{nautobot_token}}
      register: nautobot_types
      delegate_to: localhost
      run_once: true

    
    - name: Create Device Role Labels
      kentik_label:
        name: "{{ item['name'] }}"
      delegate_to: localhost
      loop: "{{ nautobot_roles.json.results }}"
      run_once: true

    - name: Create Tenant Labels
      kentik_label:
        name: "{{ item['name'] }}"
      delegate_to: localhost
      loop: "{{ nautobot_tenants.json.results }}"
      run_once: true

    - name: Create Tags Labels
      kentik_label:
        name: "{{ item['name'] }}"
      delegate_to: localhost
      loop: "{{ nautobot_tags.json.results }}"
      run_once: true

    - name: Create Device Type Labels
      kentik_label:
        name: "{{ item['display'] }}"
      delegate_to: localhost
      loop: "{{ nautobot_types.json.results }}"
      run_once: true

    - name: Create Device
      kentik_device:
        device_name: "{{ inventory_hostname }}"
        device_sample_rate: 10
        plan_name: Free Flowpak Plan
        site_name: "{{ location }}"
        sending_ips: ["{{ primary_ip4 }}"]
        device_snmp_ip: "{{ primary_ip4 }}"
        device_snmp_community: "myPreciousCommunity"
        labels: ["{{ device_roles | join(',') }}","{{ tags| join(',') }}","{{ tenants | join(',') }}"]
      delegate_to: localhost
      environment:
       PYTHONPATH: ${ANSIBLE_LIBRARY}:{{playbook_dir}}/library
       ANSIBLE_LIBRARY: ${ANSIBLE_LIBRARY}:{{playbook_dir}}/library

